name: Hello World Pipeline

on:
  push:        # Le pipeline s’exécute à chaque push
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher Hello World
        run: echo "Hello World depuis le pipeline !"

      - name: Afficher l’heure
        run: date
