name: setup

on:
  push:        
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    #init de mariadb
    services:
      mariadb:
        image: mariadb:10.3.34
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: pm2
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql

      - name: php dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm #obligatory

      - name: js dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build

      - name: php tests
        run: php artisan test -p

#         artisan:test 
#         Run php artisan:test
# Could not open input file: artisan:test



