name: setup

on:
  push:        
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql

      - name: php dependencies
        run: |
          cd pm2etml-apps-main
          composer install --no-interaction --prefer-dist

      - name: Prepare Laravel
        run: |
          cd pm2etml-apps-main
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Run PHP tests
        run: php artisan test -p

