name: setup

on:
  push:        
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    #init de mariadb
    services:
      mariadb:
        image: mariadb:10.3.34
        env:
          MARIADB_ROOT_PASSWORD: 123
          MARIADB_DATABASE: pm2
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      # repo checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # setup php (+ extentions qui sont souvent utilisées with laravel)
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' #v demandée dans readme - 8.1
          extensions: mbstring, pdo, pdo_mysql

      - name: php dependencies
        run: composer install --no-interaction --prefer-dist #pas de questions, telecharge zip 

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm #obligatory

      - name: js dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build

      - name: php tests
        run: php artisan test -p

#         artisan:test 
#         Run php artisan:test
# Could not open input file: artisan:test


#
      - name: attendre MariaDB
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: db config 
        run: |
          # Auth fake
          echo "FAKE_AUTHENTICATOR_PASSWORD=123456789" >> .env
          # echo "AUTHENTICATOR=local" >> .env
          echo "AUTHENTICATOR_ENDPOINT_V2=http://localhost" >> .env

      #à supprimmer
      - name: Show .env
        run: cat .env


      - name: Run migrations
        run: php artisan migrate:fresh --seed


